### PR TITLE
Oliveralbrecht73/add hometown

### PR DESCRIPTION
**Pull request by oliveralbrecht73**
### Description of Change

- An enhancement to our core product :smiley:
- Yet another great fix for #8 

### Test results

- Did you do any localized testing?

### Who should know about the change?

- Noone?

### CODE REVIEW

**Comment by PatBMW** [comment]
and another great feature without a testcase ??
Please add at least a file called test.md

**Review by mttkrss — APPROVED** [review]
Yeah, seems about right.

**Comment by PatBMW** [comment]
@oliveralbrecht73 looks good to me, know!

**Review by PatBMW — APPROVED** [review]
Negroni sounds good!

**Pull request merged**
