### PR TITLE
add hometown BerndHorn

### LINKED ISSUE #6: Create new File - stoe
Be sure to fill out the template below when submitting a new Issue!

- **Description:** _Enter description here_

### LINKED ISSUE #9: New File - Bernd
Be sure to fill out the template below when submitting a new Issue!

- **Description:** _Enter description here_

### PR DESCRIPTION
**Pull request by BerndHorn**
### Description of Change

- An enhancement to our core product :smiley:
- Closes #9 
- Closes #6
- Fixes #6
- Addresses #1

### Test results

- Did you do any localized testing?

### Who should know about the change?

/cc: @colossus9, @dpmex4527, @githubteacher

### CODE REVIEW

**Review by BerndHorn — COMMENTED** [review]
changes are ok. Bernd.

**Comment by BerndHorn** [comment]
Leave a comment

**Comment by oliveralbrecht73** [comment]
beautiful

**Review by stoe — APPROVED** [review]
🐙🐱💖 
👍 🚢 it

**Pull request merged**
